In [1]:
import ybsoc
import ybsoc_new
import numpy as np

In [34]:
k0 = 0.5
L = 2 * np.pi / k0
n_momentum_points = 9
N = 2

hbar = 1.

m_Yb = 1.

# q = 1.
# delta = 1.5486
# omega_R = 1.0585

k_r = 1.
delta = 4.
omega_R = 0 # 3.5

gamma = 0.32
d = 2 * (2 * np.pi) / n_momentum_points

system = ybsoc.YbSOC2bodyLoss(
    d=d,
    lengths=[n_momentum_points,],
    n_particle=N,
    hbar=hbar,
    q=k_r,
    m_Yb=m_Yb,
    delta=delta,
    omega_R=omega_R,
    gamma=gamma,
    array_type='numpy'
)

new_system = ybsoc_new.YbSOC2bodyLoss(
    L=L,
    n_mometum_points=n_momentum_points,
    n_particle=N,
    hbar=hbar,
    k_r=k_r,
    m_Yb=m_Yb,
    delta=delta,
    omega_R=omega_R,
    gamma=gamma,
)

system.print_info()

153 2-particle states
2.39 KB per state (complex128)
365.77 KB for dense representation of an operator (complex128)


c:\workspace\yb-soc-two-body-loss\scripts\opalg\lattice\utils.py:11: UserWarning: Explicitly requested dtype <class 'jax.numpy.float64'> requested in array is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  position_arr = lattice_constant * jnp.array(sites_multi_indices, dtype=jnp.float64)
c:\workspace\yb-soc-two-body-loss\scripts\opalg\lattice\utils.py:17: UserWarning: Explicitly requested dtype <class 'jax.numpy.float64'> requested in array is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  site_index_arr = jnp.array(sites_multi_indices, dtype=jnp.float64)


In [35]:
dense = system.dense_hamiltonian(kinetic=True, interaction=False)

In [36]:
dense_new = new_system.dense_hamiltonian(kinetic=True, interaction=False)

In [37]:
system.momentums

[Array([0.], dtype=float32),
 Array([0.50000006], dtype=float32),
 Array([1.0000001], dtype=float32),
 Array([1.5000002], dtype=float32),
 Array([2.0000002], dtype=float32),
 Array([-1.9999998], dtype=float32),
 Array([-1.4999995], dtype=float32),
 Array([-0.9999995], dtype=float32),
 Array([-0.49999952], dtype=float32)]

In [38]:
new_system.momentums

[np.float64(-2.0),
 np.float64(-1.5),
 np.float64(-1.0),
 np.float64(-0.5),
 np.float64(0.0),
 np.float64(0.5),
 np.float64(1.0),
 np.float64(1.5),
 np.float64(2.0)]

In [ ]:
new

In [39]:
np.sort(np.diag(dense))

array([-3.87500024+0.j, -3.87499976+0.j, -3.75      +0.j, -3.50000024+0.j,
       -3.5       +0.j, -3.37500048+0.j, -3.37500024+0.j, -3.375     +0.j,
       -3.37499976+0.j, -3.00000024+0.j, -2.875     +0.j, -2.75000024+0.j,
       -2.74999976+0.j, -2.37500024+0.j, -2.375     +0.j, -2.        +0.j,
       -1.87500024+0.j, -1.87499976+0.j, -1.50000024+0.j, -1.5       +0.j,
       -0.875     +0.j, -0.87499928+0.j, -0.74999952+0.j, -0.74999905+0.j,
       -0.37499952+0.j, -0.37499928+0.j,  0.        +0.j,  0.12499976+0.j,
        0.125     +0.j,  0.125     +0.j,  0.12500024+0.j,  0.24999976+0.j,
        0.24999976+0.j,  0.25000024+0.j,  0.25000024+0.j,  0.25000072+0.j,
        0.49999976+0.j,  0.5       +0.j,  0.5       +0.j,  0.50000024+0.j,
        0.50000095+0.j,  0.62499976+0.j,  0.62499976+0.j,  0.62499976+0.j,
        0.625     +0.j,  0.625     +0.j,  0.625     +0.j,  0.62500024+0.j,
        0.62500048+0.j,  0.62500072+0.j,  0.62500119+0.j,  0.99999976+0.j,
        1.        +0.j,  

In [40]:
np.sort(np.diag(dense_new))

array([-2.   +0.j, -2.   +0.j, -2.   +0.j, -2.   +0.j, -1.875+0.j,
       -1.875+0.j, -1.875+0.j, -1.875+0.j, -1.875+0.j, -1.875+0.j,
       -1.875+0.j, -1.875+0.j, -1.5  +0.j, -1.5  +0.j, -1.5  +0.j,
       -1.5  +0.j, -1.5  +0.j, -1.5  +0.j, -1.5  +0.j, -1.5  +0.j,
       -0.875+0.j, -0.875+0.j, -0.875+0.j, -0.875+0.j, -0.875+0.j,
       -0.875+0.j, -0.875+0.j, -0.875+0.j, -0.875+0.j, -0.875+0.j,
        0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,
        0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,  0.   +0.j,
        0.   +0.j,  0.   +0.j,  1.   +0.j,  1.125+0.j,  1.125+0.j,
        1.125+0.j,  1.125+0.j,  1.125+0.j,  1.125+0.j,  1.125+0.j,
        1.125+0.j,  1.125+0.j,  1.125+0.j,  1.125+0.j,  1.125+0.j,
        1.125+0.j,  1.125+0.j,  1.25 +0.j,  1.25 +0.j,  2.   +0.j,
        2.   +0.j,  2.   +0.j,  2.   +0.j,  2.   +0.j,  2.   +0.j,
        2.   +0.j,  2.   +0.j,  2.   +0.j,  2.   +0.j,  2.   +0.j,
        2.   +0.j,  2.   +0.j,  2.   +0.j,  2.125+0.j,  2.125+

In [30]:
np.sum(np.abs(np.sort(np.diag(dense)) - np.sort(np.diag(dense_new))))

np.float64(5.7220458984375e-06)

In [6]:
dense = system.dense_hamiltonian(kinetic=True, interaction=True)
spectrum, _ = np.linalg.eig(dense)

In [7]:
spectrum

array([24.57205174-0.03382717j, 24.80372066-0.02574269j,
       24.28459835-0.02195297j, ..., 12.53785221-0.07639437j,
        4.71202406-0.07639437j,  5.82321415-0.07639437j], shape=(8568,))

In [8]:
dense_new = new_system.dense_hamiltonian(kinetic=True, interaction=True)
spectrum_new, _ = np.linalg.eig(dense_new)

In [9]:
spectrum_new

array([ 1.75-0.0127324j , -1.75-0.0127324j , -1.75-0.02546479j, ...,
        1.75-0.02546479j,  1.75-0.0127324j , -1.75-0.0127324j ],
      shape=(8568,))

In [11]:
np.sum(np.abs(np.sort(spectrum) - np.sort(spectrum_new)))

np.float64(56692.8060393076)